### ISSUE TITLE
not working with postcss-bem-linter

### ISSUE THREAD

**Issue by VinSpee** [code42day/postcss-cli#21]
see postcss/postcss-bem-linter#55

Is this configuration compatible with postcss-cli? It seems as though it's not. when doing:

``` bash
postcss --use postcss-bem-linter --postcss-bem-linter.namespace "br" ./src/styles/main.css
```

I'm getting the error

``` bash
[TypeError: Cannot read property 'initial' of undefined]
```

I assume it's because of this's plugin's unusual configuration signature - any thoughts?

**Comment by pirxpilot** [comment]
`postcss-cli` can only work with plugins that conform to [postcss plugin guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#14-create-plugin-by-postcssplugin)
Looks like `postcss-bem-linter` does not accept options object as a first parameter of the plugin function.

**Comment by VinSpee** [comment]
thanks - I'll add that to my issue in their repo.

**Comment by davidtheclark** [comment]
Two comments related to this:
- The plugin guidelines do not state that plugins must accept an options object as the first and only parameter of the plugin function. They just say to use the plugin function (and the example shows that it can take arguments). So `postcss-bem-linter` is conforming just fine to the guidelines: but the `--plugin.option` argument for `postcss-cli` is limited. If the `--plugin.option` argument is only good for plugins of a particular function signature, there should be a warning about it in the docs.
- I was thinking about changing the options for `postcss-bem-linter` to a single object with one option that takes an object for its value --- but `postcss-cli` probably couldn't handle that, either, in this `--plugin.option` syntax. Could it? --- could you pass an object as the "value"?

Maybe the solution is to encourage people to use a configuration file instead of the `--plugin.option` argument for any plugins that don't fit one particular signature (single option that is a flat object).

**Comment by pirxpilot** [comment]
I am pretty sure that `--plugin.option` is _not_ limited in the way you describe it. You can absolutely pass multiple options and they do not  have to be flat.
You can pass:

```
--postcss-bem-linter.x.b 1 --postcss-bem-linter.y.c 2
```

And the resulting options will look like this:

```
{
 x: { b: 1 },
 y: { c: 2 }
}  
```

You can just use configuration file if your config is that complicated but it does not mean that `postcss-cli` documentation should tell people to do that.

And yes - if you change `bem-linter` signature it'll start working with postcss-cli - and not just with _single option that is a flat object_.

That said: if plugin functions - as you seem to imply - can have multiple arguments how do you propose a generic plugin runner (there are more than `postcss-cli`) should deal with that?

**Comment by davidtheclark** [comment]
> You can absolutely pass multiple options and they do not have to be flat.

Ok, great.

> if plugin functions - as you seem to imply - can have multiple arguments how do you propose a generic plugin runner (there are more than postcss-cli) should deal with that

It's a problem to confront, because I'm not just implying -- plugins, being JS functions, can indeed accept multiple arguments. `postcss-bem-linter` works fine in runners that use JS (e.g. `gulp-postcss`). Maybe it won't work so well in runners with limitations. Maybe it causes enough problems that it should be added to the plugin guidelines that there's only a single argument that is an object --- @ai?

**Comment by pirxpilot** [comment]
`grunt` and `gulp` runners expect plugins/processors be instantiated and initialized **before** they are passed to the runner - so yeah - they can accommodate diverse plugin function signature. Not sure if it can be implemented easily in a runner that, like `postcss-cli`, instantiates and initializes processors.
That said: if `postcss` plugins with multi-argument initialization function are common (are they?) we could add support for them through .js config format.
Unless someone has a better idea...

BTW: [plugins-guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#14-create-plugin-by-postcssplugin) refer to a plugin method with a single `opts` argument. It's entirely possible that it's just meant to be an example and not a recommendation. Would be great if it's clarified there.
