### ISSUE TITLE
Can't seem to watch file(s)?

### ISSUE THREAD

**Issue by corysimmons** [code42day/postcss-cli#46]
So I'm trying to watch files with:

`postcss --local-plugins -u ./lib/index.js -d playground/dist -w 'playground/src/**/*.css'`

I would expect that to watch my `src` dir for any css files (recursively), process them with `./lib/index.js` and then output the compiled files and directories to `playground/dist`.

Instead it throws the error:

```
Users/cory/Desktop/postcss-ant-grid/node_modules/chokidar/index.js:553
    throw new TypeError('Non-string provided as watch path: ' + paths);
    ^

TypeError: Non-string provided as watch path
```

Anyway, then I tried `postcss --local-plugins -u ./lib/index.js -d playground/dist -w playground/src/style.css` and it threw the same error. :(

If I remove the `-w` it compiles as expected.

What am I doing wrong?

**Comment by pirxpilot** [comment]
hey @FND - could you have a look when you have a chance

**Comment by FND** [comment]
The `--watch` option was designed to determine the list of source files automatically based on the _entry point(s)_. Thus the expectation is that there's some sort of manifest (typically `index.css`) which already has all the information, namely references to other files (typically via `@import` - though that depends on the respective plugin). The advantage is that you don't have to redundantly specify the list of source files on the command line, out of band.

However, right now this means you need some sort of plugin that somehow determines this list of referenced files for you (details below). If that turns out to be an unreasonable assumption, we should consider how we can best support your use case as well - but it's hard to tell for me right now because I don't know what your `./lib/index.js` plugin represents.

The canonical example right now is postcss-import:
https://gist.github.com/FND/8334c63229867e33feae
There `index.css` references `foo.css` and `bar.css`, with the latter referencing `baz.css`. postcss-import determines this dependency graph, then postcss-cli's `onImport` hook is used to invoke `watchCSS`, thus making sure the corresponding list of files is monitored for changes.

**Comment by pirxpilot** [comment]
postcss-cli is now maintanained in [postcss/postcss-cli](https://github.com/postcss/postcss-cli)
Please reopen this issue there.
