### ISSUE TITLE
why I set postcss.json,it not work?

### ISSUE THREAD

**Issue by shunhua126** [code42day/postcss-cli#56]
postcss.json in root directory of my project
{
	"postcss-px-to-viewport": {
		"viewportWidth": 750,
		"viewportHeight": 1334
	}
}
package.json 
"scripts": {
    "px2vw": "postcss -u postcss-px-to-viewport -c postcss.json -o dist/css/school-vw.css src/css/school.css"
  }

**Comment by melitele** [comment]
What happens vs. what is expected? Best if you link to a working - or not working as may be the case :-) - example.

**Comment by ai** [comment]
Seems like `postcss-cli` doesn’t apply config. It happens because `-c` accept the only dir and always look for `postcss.config.js`.

It is second time (first was in gitter chat) on the week when users were confused with this behavior. Suggestion:

1. Allow to pass files (if dir was passed to the argument, look for `dir + postcss.config.js`
2. Show warning if the user passed a file instead of the dir.

**Comment by pirxpilot** [comment]
@shunhua126 config file format and command line look OK to me, but just to make sure why don't you attach `postcss.json` file and `package.json` file it to the issue and I'll have another look.

BTW make sure that you have [postcss-cli-simple] and not [postcss-cli] installed if that's what you want to use though (quick look in your `package.json` dependencies should clear that up.)

[postcss-cli-simple]: https://www.npmjs.com/package/postcss-cli-simple
[postcss-cli]: https://www.npmjs.com/package/postcss-cli
