### ISSUE TITLE
Support for STDIN and STDOUT?

### ISSUE THREAD

**Issue by remorse** [code42day/postcss-cli#57]
Hi! I'd like to use postcss-cli-simple as a part of a piped workflow. Is there a way to have it read from STDIN and write to STDOUT? I tried `-o -`, which didn't work. It also doesn't accept '-' as an input file.

I looked at postcss-cli, but it won't let me specify options to postcss modules as a part of the command, and for my use case creating a config file would not work.

Thanks,
Ricky

**Comment by pirxpilot** [comment]
I removed stdin/stdout support from `postcss-cli-simple` shortly after `postcss-cli` spin-off. I wanted to keep it simple and I removed all the extra functionality (and the extra deps) that were not related to the core functionality.
You can either rummage through the history and bring it back in your fork, or - and this may be easier - write a  wrapper script that cats stdin to a temp file, and then cats out the output file to stdout. But you probably know that already...

**Comment by sntran** [comment]
I was very excited to see a simpler version of `postcss-cli` that does not occupy [5MB](https://packagephobia.now.sh/result?p=postcss-cli) and a bunch of extra dependencies, that I could use in my Makefile.

Unfortunately, without at least reading from stdin, it's tricky for me to use, as I have to compile my Sass file to CSS first before sending to PostCSS. Writing a wrapper script is fine, but in that case I may as well write a node script using `postcss` JS API.

I got a workaround using process substitution in case anybody is interested in (also a note for my future self):

```shell
styles() { postcss --use=autoprefixer --output=$2 <(sass --style=compressed $1); }; styles input output
```

If used as an NPM script, you need to set NPM's `script-shell` config to `bash`, since the default `sh` does not understand process substitution.

**Comment by pirxpilot** [comment]
Another way of using `sass` and `postcss` in your Makefiles is to separate _sassing_ stage from _postcssing_ stage:

```make
%.sass.css: %.sass
    sass [sass options] $< $@

%.css: %.sass.css
    postcss [postcss options] --output $@ @<

style: dist/main.css dist/another.css
```

 Make will take care of finding the right sequence of operations, it will only process what actually needs processing and it will even clean up the intermediary files for you - IOW it will do exactly what it is supposed to do. Not external scripts or pipes necessary.
